In [71]:
import numpy as np
import gym
import random
import time

In [92]:
env = gym.make('LunarLander-v2')

#env = gym.make('')
#dir(gym.make)
#gym.make.__str__()
env.render()

AttributeError: module 'gym.envs.box2d' has no attribute 'LunarLander'

In [84]:
# all possible actions our agent can take
action_space_size = env.action_space.n
# combination of all states the agent can be in
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [85]:
episodes = 10000
max_steps_per_episode = 100 # maximum number of steps our agent is allowed to take in a single episode

# learning parameters
learning_rate = 0.1 # alpha
discount_rate = 0.99 # gamma

# exploration paramaters
epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
epsilon_decay_rate = 0.1

In [67]:
print(env.reset())

0


In [68]:
rewards_all_episodes = []

for episode in range(episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration and exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > epsilon:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        # info = diagnostic information
        # update q_table for Q(s,a)
        q_table[state,action] = q_table[state,action] *(1- learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode +=reward
        
        if done == True:
            break
            
            
    # Decaying exploration rate using exponential decay
    #
    epsilon = min_epsilon + (max_epsilon - min_epsilon)* np.exp(-epsilon_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)

In [69]:
# calculating and printing the moving average
rewards_per_thousand = np.split(np.array(rewards_all_episodes),episodes/1000)
count = 1000

print('********* Average reward per thousand ********\n')
for r in rewards_per_thousand:
    print(count, ':', str(sum(r/1000)))
    count += 1000

********* Average reward per thousand ********

1000 : 0.6800000000000005
2000 : 0.6840000000000005
3000 : 0.6990000000000005
4000 : 0.6980000000000005
5000 : 0.6710000000000005
6000 : 0.6750000000000005
7000 : 0.7110000000000005
8000 : 0.6850000000000005
9000 : 0.7020000000000005
10000 : 0.6900000000000005


In [70]:
print(q_table)

[[0.55287972 0.520951   0.52808813 0.5085286 ]
 [0.30694424 0.32022241 0.31395321 0.51389577]
 [0.44282952 0.43489241 0.42035327 0.48713595]
 [0.31413113 0.3537179  0.18985552 0.46484886]
 [0.57684629 0.47311454 0.46745299 0.34292566]
 [0.         0.         0.         0.        ]
 [0.33620199 0.16779361 0.16740544 0.08161492]
 [0.         0.         0.         0.        ]
 [0.28671936 0.35559468 0.44866412 0.61722056]
 [0.33538277 0.65304808 0.59930925 0.31219885]
 [0.66115833 0.50908829 0.42403673 0.32727643]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.50698479 0.53338983 0.76551465 0.47919871]
 [0.71192772 0.91329172 0.77231993 0.77229828]
 [0.         0.         0.         0.        ]]
